version: '3'
services:
  mysqldb: 
    image: mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=porte_ouverte
      - MYSQL_ROOT_PASSWORD=CeciEstUnMDPROOTsecure$$784523
      - MYSQL_USER=PorteOuverte
      - MYSQL_PASSWORD=&52&TQn2iy
    restart: always
    ports:
      - 7777:3306
    volumes:
      - dbPorteOuverte:/var/lib/mysql
      
  backend: 
    build: back/.
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8080:80
    environment:
      - DB_HOST=mysqldb
      - DB_NAME=porte_ouverte
      - DB_USER=PorteOuverte
      - DB_PASSWORD=&52&TQn2iy
      - DB_PORT=3306
      - EMAIL_USER=guillemin.mathieu@outlook.com
      - EMAIL_PASS=&52&TQn2iy&&A8u63q5c


  frontend:
    build: front/.
    restart: always
    depends_on:
      - backend
    ports: 
     - 3000:80
    environment:
      - REACT_APP_API_URL=http://localhost:8080/

volumes:
  dbPorteOuverte: